# Generated by Django 4.0.3 on 2022-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_new_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedln_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
