# Generated by Django 4.0.3 on 2022-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_project',
            name='mentor_name',
            field=models.CharField(max_length=100),
        ),
    ]
