# Generated by Django 4.0.3 on 2022-06-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='query_ans',
        ),
    ]
