# Generated by Django 4.0.3 on 2022-06-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_resolved_queries_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolved_queries',
            name='project_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resolved_queries',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
