# Generated by Django 4.0.3 on 2022-06-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_resolved_queries_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='linkedln_username',
        ),
    ]
