# Generated by Django 4.0.3 on 2022-06-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_student_linkedln_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
