# Generated by Django 4.0.3 on 2022-06-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='highest_degree',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='github_username',
        ),
    ]
