# Generated by Django 4.0.3 on 2022-06-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_student_github_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='github_username',
        ),
    ]
