# Generated by Django 4.0.3 on 2022-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_student_github_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='new_project',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
