# Generated by Django 4.0.3 on 2022-06-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_new_project_project_desc_existing_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='existing_projects',
            name='interest',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='existing_projects',
            name='project_desc',
            field=models.TextField(max_length=400),
        ),
    ]
