# Generated by Django 4.0.3 on 2022-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_existing_projects_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='experiance',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='student',
            name='github_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
