# Generated by Django 4.0.3 on 2022-07-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_uploaded_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploaded_Photo',
        ),
    ]
