# Generated by Django 4.0.3 on 2022-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_delete_uploaded_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
