# Generated by Django 4.0.3 on 2022-07-05 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_teacher_name_alter_teacher_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('project_name', models.CharField(max_length=150)),
                ('start_date', models.CharField(max_length=150)),
                ('end_date', models.CharField(max_length=150)),
                ('progress', models.CharField(max_length=300)),
                ('resources', models.CharField(max_length=300)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
