# Generated by Django 4.0.3 on 2022-07-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='mentor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
