# Generated by Django 4.0.3 on 2022-07-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_progress_mentor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='github_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
